app/contas/__init__.py
from flask import Blueprint

contas = Blueprint('contas', __name__)

from app.contas import views

app/contas/views.py
from flask import redirect, render_template, request, url_for
from app import db
from app.contas import contas
from app.decorators import permission_required
from app.models import Permission, Conta
from flask_login import login_required, current_user

@contas.route("/")
def index():
    contas = Conta.query.filter_by(titular_id=current_user.id, enabled=True).all()
    tipo = "padrão"
    if current_user.role.has_permission(Permission.ADMIN):
        contas = Conta.query.all()
        tipo = "admin"

    return render_template("contas/index.html", contas=contas, tipo=tipo)

@contas.route("/desabilitar/<id>")
@login_required
@permission_required(Permission.DESABILITAR)
def desabilitar(id):
    conta = Conta.query.filter_by(id=id, enabled=True).first()
    if conta:
        conta.enabled = False

        db.session.add(conta)
        db.session.commit()

        return redirect(url_for("contas.index"))
    return redirect(url_for("contas.index"))

@contas.route("/habilitar/<id>")
@login_required
@permission_required(Permission.DESABILITAR)
def habilitar(id):
    conta = Conta.query.filter_by(id=id, enabled=False).first()
    if conta:
        conta.enabled = True

        db.session.add(conta)
        db.session.commit()

        return redirect(url_for("contas.index"))
    return redirect(url_for("contas.index"))

@contas.route("/criar", methods=["GET", "POST"])
@login_required
@permission_required(Permission.CRIAR)
def criar():
    if request.form:
        conta = Conta()
        conta.saldo = request.form.get("saldo")
        conta.titular_id = current_user.id

        db.session.add(conta)
        db.session.commit()

        return redirect(url_for("contas.index"))
    return render_template("contas/criar.html")

app/templates/contas/criar.html
{% extends 'base.html' %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-6 text-center">
            <h2>Criar Conta</h2>
        </div>
    </div>
    <form method="POST">
        <div class="row justify-content-center">
            <div class="col-md-4 text-center">
                <label for="saldo">Saldo Inicial</label>
                <input class="form-control" type="number" step=".01" id="saldo" name="saldo" required>
            </div>
        </div>
        <div class="row mt-3 justify-content-center">
            <div class="col-md-4 text-center">
                <input class="btn btn-primary" type="submit" value="Criar Conta">
            </div>
        </div>
    </form>    
{% endblock %}

app/templates/contas/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-4">
            <h2>Lista de Contas</h2>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <table class="table">
                <thead>
                    <tr>
                        <th>Número da Conta</th>
                        <th>Saldo</th>
                        {% if tipo == "admin" %}
                        <th>Titular</th>
                        <th>Status</th>
                        {% endif %}
                        <th>Opções</th>
                    </tr>
                </thead>
                <tbody>
                    {% if not contas %}
                        <tr>
                            <td class="text-center" colspan="3">Este usuário não tem contas</td>
                        </tr>
                    {% else %}
                        {% for conta in contas %}
                            <tr>
                                <td>{{ conta.id }}</td>
                                <td>{{ conta.saldo }}</td>
                                {% if tipo == "admin" %}
                                <td>{{ conta.titular.nome }}</td>
                                <td>{% if conta.enabled %} Habilitada {% else %} Desabilitada {% endif %}</td>
                                {% endif %}
                                <td>
                                    {% if conta.enabled %}
                                    <a href="{{ url_for('contas.desabilitar', id=conta.id) }}" class="btn btn-danger btn-icon"><i class="fa-solid fa-x"></i></a>
                                    {% else %}
                                    <a href="{{ url_for('contas.habilitar', id=conta.id) }}" class="btn btn-success btn-icon"><i class="fa-solid fa-check"></i></a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}